### ISSUE TITLE
Invalid GeoJSON when using NULL on feature member ID

### ISSUE THREAD

**Issue by iH8** [mapbox/geojsonhint#24]
This is not according to specification. The only thing that is stated in the spec. about the identifier is the following:

>If a feature has a commonly used identifier, that identifier should be included as a member of the feature object with the name "id".

http://geojson.org/geojson-spec.html#feature-objects

Since nothing else is mentioned about the type of ID, it should adhere to the JSON spec where the property of an object can be any of the following: String, Number, null, true, false, Array or Object

**Comment by tmcw** [comment]
This part of the validator is written against the [draft spec](https://github.com/geojson/draft-geojson/blob/master/middle.mkd#feature-object) which specifies a string or number, not null or any other type.

**Comment by iH8** [comment]
Ok, i see. Wasn't aware. I was in the midst of some confusion about this because of inconsistencies between geojson.io and geojsonhint.com All cleared up now. Sorry for the disturbance.
