### ISSUE TITLE
polygon with crossing edges

### ISSUE THREAD

**Issue by franckl** [mapbox/geojsonhint#25]
Would it be possible to add a "polygon with crossing edges" warning in geojsonhint ?
mongodb 2dsphere index doesn't support such polygons and I would like detec it in advance

![image](https://cloud.githubusercontent.com/assets/3875803/6258973/69565f7a-b79b-11e4-94f1-6b1d547b6aa2.png)

**Comment by tmcw** [comment]
Yep, definitely a good idea to start including some warnings. I think [turf-kinks](https://github.com/Turfjs/turf-kinks) might help us out here. Note of course that crossing rings are valid in geojson, so these won't be errors.

**Comment by tmcw** [comment]
Folding into #48 that proposes this amongst other geometry validation steps.
