### ISSUE TITLE
Any way to specify expected geojson object type?

### ISSUE THREAD

**Issue by sckott** [mapbox/geojsonhint#27]
E.g., 

```js
geojsonhint.hint(<object>, expected = "point")
```

Would be nice to be able to not only know if the geojson passes the linter, but if the object passed in is actually a `Point` if you expect it to be - Perhaps this is out of scope.

**Comment by tmcw** [comment]
This is equivalent to

```js
!geojsonhint.hint(<object>).length && <object>.type === 'Point';
```

Which I think is more clear

**Comment by sckott** [comment]
@tmcw thanks, makes sense
