### ISSUE TITLE
Non-number members in coordinates ignored

### ISSUE THREAD

**Issue by kkaefer** [mapbox/geojsonhint#28]
The spec says that all members of a position array must be numbers, but this code doesn't check that. It also doesn't check that there are at least two members.

```json
{
  "type": "Point",
  "coordinates": [ 1, 2, "f" ]
}
```

**Comment by tmcw** [comment]
Hm, are you sure? Just added a test case with this input and it found the error.

**Comment by tmcw** [comment]
Both of these constraints are enforced here: https://github.com/mapbox/geojsonhint/blob/master/index.js#L73-L95

**Comment by tmcw** [comment]
Closing: please reopen if you can replicate the issue in a test @kkaefer
