### ISSUE TITLE
Geometry null

### ISSUE THREAD

**Issue by fxi** [mapbox/geojsonhint#52]
Hi,

"geometry: null" should be listed as an error. Turf ( or Mapbox gl) are throwing an error with this.

Thanks !

Maybe something like this : 
```{js}
        if (geom === null) {
            errors.push({
                message: 'geometry could not be null',
                line: geom.__line__
            });
        }
```

This will fail: 

```{json}
{
  "type": "FeatureCollection",
  "crs": {
    "type": "name",
    "properties": {
      "name": "urn:ogc:def:crs:OGC:1.3:CRS84"
    }
  },
  "features": [
    {
      "type": "Feature",
      "properties": {
        "Label": "Tertiary"
      },
      "geometry": null
    },
    {
      "type": "Feature",
      "properties": {
        "Label": "Secondary"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            66.599966,
            36.997548
          ],
          [
            66.603196,
            36.99737
          ],
          [
            66.607052,
            36.997655
          ]
        ]
      }
    }
  ]
}
```

**Comment by sgillies** [comment]
@fxi `"geometry": null` means the feature is unlocated and is valid GeoJSON: https://tools.ietf.org/html/rfc7946#section-3.2. It could be useful to print a message that notes a feature is unlocated, but this is not exactly a data error.

**Comment by fxi** [comment]
Thanks for your quick reply !

You are right and I should have checked this before posting something.

Moreover, my example works well in mapbox gl. 

http://jsbin.com/dehalawuhe/edit?html,output

Thanks again !

**Comment by tmcw** [comment]
@fxi can you replicate this error in _both_ mapbox-gl-js and turf? Can you be more specific about both? mapbox-gl-js's GeoJSON processing infrastructure already [has a test confirming null geometry support](https://github.com/mapbox/geojson-vt/blob/50114b66c84b606cc71b0484dd660b9fa7e9bf93/test/test-full.js#L35-L39), so it should be able to handle null geometries correctly.

**Comment by fxi** [comment]
@tmcw Thanks, but I was on the wrong track with the null values, I'm sorry. Both mapbox-gl-js and turf seems to handle this well. I've removed the null geometry but I still get an error when adding a [specific file](https://www.dropbox.com/s/34n6wxri83xsdnl/roads.geojson?dl=0) as source in mapbox-gl-js. For your information, I'm trying to do a small experiment with a mapbox-gl-js with a multiple large files, drag and drop functionality: http://bl.ocks.org/fxi/b7f1af5981432296bfafec70a95fd9b6. And naturally, there is surprises everywhere, this is why I put aside my crystal ball and looked for a smart tool like geojsonhint to do the validation job. But it's not a validation thing, after all.
