### ISSUE TITLE
Inverted RightHandRule logic?

### ISSUE THREAD

**Issue by tyrasd** [mapbox/geojsonhint#54]
As far as I can tell, the logic introduced in 957389fe332022fe3bf1825b0c6e73260bc81c13 (for #48 and rfc7946) is just the opposite of what it should be‽

I've created some test data, where only the counterclockwise winding gets a warning by geojsonhint: https://gist.github.com/tyrasd/2fcc5aefd988bf6b02a29b8c6e63ef9b (you can also test that by posting the data into http://geojsonlint.com/, which has [recently updated](https://github.com/JasonSanford/geojsonlint.com/commit/d6c63b36bd8c2d12b9a008ce8cf461586f7c8da2) its copy of geojsonhint).

    $ geojsonhint counterclockwise.geojson 
        6:1  warning  Polygons and MultiPolygons should follow the right-hand rule
      
      ⚠ 1 warning
    $ geojsonhint clockwise.geojson 
    $

Here's what the specs say about ring winding:

>  A linear ring MUST follow the right-hand rule with respect to the area it bounds, i.e., exterior rings are counterclockwise, and holes are clockwise.

**Comment by perrygeo** [comment]
@tyrasd good catch, I'll work on fixing this ASAP.

**Comment by rurban** [comment]
The problem is that the rhr check is wrong, by using angles. You only should do the cross-product for all edges.
