### ISSUE TITLE
Define behavior for SHOULD / SHOULD NOT rules

### ISSUE THREAD

**Issue by romanzoller** [mapbox/geojsonhint#57]
[RFC7946](https://tools.ietf.org/html/rfc7946#section-3.1.1) says:
> Implementations SHOULD NOT extend positions beyond three elements because the semantics of extra elements are unspecified and ambiguous.

And [RFC2119](https://www.ietf.org/rfc/rfc2119.txt) says:
> 4. SHOULD NOT   This phrase, or the phrase "NOT RECOMMENDED" mean that there may exist valid reasons in particular circumstances when the particular behavior is acceptable or even useful, but the full implications should be understood and the case carefully weighed before implementing any behavior described with this label.

So I would assume that having positions with more than three elements would be acceptable "in particular circumstances", but geojsonhint refuses them [with an error](https://github.com/mapbox/geojsonhint/blob/f77ab85f1cde8643245eef877fb483bd4f1227f3/lib/object.js#L134-L139).

I think this should either be a warning, or it should be made clear that geojsonhint interprets violations SHOULD / SHOULD NOT rules of the spec as errors.

**Comment by tmcw** [comment]
This should be made a warning: we already make the coordinate precision warning [level: message](https://github.com/mapbox/geojsonhint/blob/master/lib/object.js#L165) and we should make the position extension warning a message as well.
