### ISSUE TITLE
Warn about integer values that are too large

### ISSUE THREAD

**Issue by sgillies** [mapbox/geojsonhint#64]
See https://tools.ietf.org/html/rfc7493#section-2.2:

> An I-JSON sender cannot expect a receiver to treat an integer whose
> absolute value is greater than 9007199254740991 (i.e., that is
> outside the range `[-(2**53)+1, (2**53)-1])` as an exact value.

We should warn about integers outside this range.

**Comment by jfirebaugh** [comment]
I support this. We'd need to switch the internal parser from jsonlint-lines to [json-bigint](https://www.npmjs.com/package/json-bigint).
