### ISSUE TITLE
async usage?

### ISSUE THREAD

**Issue by contra** [mapbox/geojsonhint#71]
for web applications where users can send up geojson, it would be great if this gave the event loop some time to breathe especially on large multipolygons. the recursive tight loops will choke it up for up to a second sometimes, which is really bad.

possible solutions:
- run it in a worker
- use setImmediate between loop iterations so it doesn't choke the process for a second straight

if interested i can send a PR, otherwise will fork as `geojsonhint-async`

**Comment by sgillies** [comment]
@contra :+1: on the async fork.
