### ISSUE TITLE
Dependency minimist causes a vulnerability warning

### ISSUE THREAD

**Issue by ruegenbfr** [mapbox/geojsonhint#78]
The current version 1.2.0 of minimist lib causes a vulnerability warning with low severity.
Please increase version number.

**Comment by littlebtc** [comment]
It is merged in repo but unfortunately it is still not released yet (#79).

Anybody on it?

**Comment by poxrud** [comment]
Latest npm registry version of _@mapbox/geojsonhint_ still has a dependancy on the vulnerable _minimist v1.2.0_ causing npm warnings. Please push the latest version to npm registry.

**Comment by pathmapper** [comment]
This affects `mapbox-gl-draw`, see https://github.com/mapbox/mapbox-gl-draw/issues/1020.

@sgillies @asheemmamoowala any chance to get a new release published to npm?

**Comment by sgillies** [comment]
v3.0.1 has been published to `@mapbox/geojsonhint`. @poxrud @pathmapper this package will be deprecated (see #83). Please begin to make plans to check GeoJSON in some other way.
